//local
GET http://localhost:3000/contacts
###
GET http://localhost:3000/contact/68d6a30ad69f7d241f9b5789

//production
###
GET https://cse341-af70.onrender.com/contacts
###
GET https://cse341-af70.onrender.com/contact/68d6a30ad69f7d241f9b5789
